MID_TEAL = "#145A5A"
DARK_TEAL = "#002832"
GREEN_TEAL = "#00674F"
SNOW_WHITE = "#E3F9FA"


HEADING_FONT_FAMILY = "Arial"  # Placeholder for narnoor font
BODY_FONT_FAMILY = "Arial"     # Placeholder for inter font

HEADER_HEIGHT = 65
FOOTER_HEIGHT = 65
TITLE_SECTION_HEIGHT = 77

HEADER_LEFT_PROPORTION = 530
HEADER_MIDDLE_PROPORTION = 860
HEADER_RIGHT_PROPORTION = 530

CS_OTHERS_PROPORTION = 682
CS_SA_EXAMS_PROPORTION = 584
GRADES_BREAKDOWN_PROPORTION = 514

HOME_SECTION_WIDTH = 80
NEXT_SECTION_WIDTH = 80